# Site settings
title: ronfe
email: me@ronfe.net
description: > # this means to ignore newlines until "baseurl:"
    ronfe
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://ronfe.io" # the base hostname & protocol for your site
twitter_username: chihungfei
github_username: ronfe 

# Build settings
markdown: kramdown
